"""
Shell Service Implementation - Real persistent shell backed by tmux

Modeled after the AIO (all-in-one) sandbox, whose shell module uses
OpenHands' CmdRunAction as execution engine combined with tmux to provide
multi-session, stateful shells. Each shell session here is a long-lived
interactive bash process running inside a dedicated tmux session, so state
(working directory, environment variables, virtualenvs, background jobs)
persists across commands — unlike the previous implementation which spawned
a fresh subprocess per command.

Command completion, exit code, user, host and cwd are detected through a
PS1 sentinel that prints a machine-readable JSON block after every command.
"""
import asyncio
import json
import logging
import os
import re
import shlex
import time
import uuid
from typing import Any, Dict, List, Optional, Tuple

import libtmux

from app.models.shell import (
    ShellExecResult, ShellViewResult, ShellWaitResult,
    ShellWriteResult, ShellKillResult, ConsoleRecord
)
from app.core.exceptions import AppException, ResourceNotFoundException, BadRequestException

# Set up logger
logger = logging.getLogger(__name__)

# PS1 sentinel markers (same idea as OpenHands' CmdOutputMetadata PS1 prompt)
PS1_BEGIN = "###PS1JSON###"
PS1_END = "###PS1END###"

# Matches a rendered PS1 sentinel block in captured tmux pane content
PS1_REGEX = re.compile(re.escape(PS1_BEGIN) + r"\n(.*?)" + re.escape(PS1_END), re.DOTALL)

# The PS1 value exported before every prompt via PROMPT_COMMAND:
# - `$?` and `$(pwd)` expand when PROMPT_COMMAND re-exports PS1 (i.e. right
#   after each command finishes), capturing exit code and working directory.
# - `\u`, `\h` and `\n` survive as-is and are rendered by bash prompt expansion.
_PS1_EXPORT = (
    "export PROMPT_COMMAND='export PS1=\""
    r"\n" + PS1_BEGIN + r"\n"
    r"{\"exit_code\": \"$?\", \"username\": \"\u\", \"hostname\": \"\h\", \"working_dir\": \"$(pwd)\"}"
    r"\n" + PS1_END + r"\n"
    "\"'"
)

# Rc file sourced by the persistent bash of every shell session
INIT_FILE = "/tmp/.manus_shell_init.sh"
INIT_FILE_CONTENT = f"""# Generated by ai-manus sandbox shell service
if [ -f "$HOME/.bashrc" ]; then
    source "$HOME/.bashrc"
fi
{_PS1_EXPORT}
export PS2=''
export PAGER=cat
export GIT_PAGER=cat
"""

# tmux pane history limit (lines); large enough for block counting to stay valid
HISTORY_LIMIT = 100000

# Special tmux key names accepted by shell_write (e.g. sending Ctrl-C)
SPECIAL_KEY_REGEX = re.compile(r"^C-[a-zA-Z]$")


class ShellDeadError(Exception):
    """Raised when the underlying tmux session/bash process has exited"""
    pass


class ShellService:
    # Store active shell sessions
    active_shells: Dict[str, Dict[str, Any]] = {}

    # Serializes shell session creation
    _create_lock: asyncio.Lock = asyncio.Lock()

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _remove_ansi_escape_codes(self, text: str) -> str:
        """Remove ANSI escape codes from text"""
        ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')
        return ansi_escape.sub('', text)

    def _get_display_path(self, path: str) -> str:
        """Get the path for display, replacing user home directory with ~"""
        home_dir = os.path.expanduser("~")
        if path.startswith(home_dir):
            return path.replace(home_dir, "~", 1)
        return path

    def _format_ps1(self, shell: Dict[str, Any]) -> str:
        """Format the command prompt from the latest shell metadata"""
        meta = shell.get("meta") or {}
        username = meta.get("username", "user")
        hostname = meta.get("hostname", "sandbox")
        display_dir = self._get_display_path(shell.get("last_cwd") or os.path.expanduser("~"))
        return f"{username}@{hostname}:{display_dir} $"

    def _ensure_init_file(self) -> None:
        """Write the bash rc file that installs the PS1 sentinel"""
        try:
            with open(INIT_FILE, "r") as f:
                if f.read() == INIT_FILE_CONTENT:
                    return
        except OSError:
            pass
        with open(INIT_FILE, "w") as f:
            f.write(INIT_FILE_CONTENT)

    # ------------------------------------------------------------------
    # tmux plumbing (synchronous — always called through asyncio.to_thread)
    # ------------------------------------------------------------------

    def _capture_sync(self, pane: libtmux.Pane) -> str:
        """Capture the full pane content including scrollback history"""
        result = pane.cmd("capture-pane", "-J", "-p", "-S", "-", "-E", "-")
        if result.stderr and not result.stdout:
            raise ShellDeadError("\n".join(result.stderr))
        # `-J` joins wrapped lines but preserves trailing spaces (tmux pads
        # lines to the pane width on some versions, e.g. 3.2a), so strip them
        return "\n".join(line.rstrip() for line in result.stdout)

    def _parse_blocks(self, content: str) -> List[Tuple[re.Match, Dict[str, Any]]]:
        """Find all valid PS1 sentinel blocks (match + parsed metadata)"""
        blocks = []
        for match in PS1_REGEX.finditer(content):
            try:
                meta = json.loads(match.group(1).strip(), strict=False)
                if isinstance(meta, dict):
                    blocks.append((match, meta))
            except json.JSONDecodeError:
                # e.g. the echoed rc file line or partially rendered prompt
                continue
        return blocks

    def _create_tmux_shell_sync(self, session_id: str, start_dir: str) -> Tuple[libtmux.Session, libtmux.Pane]:
        """Create a tmux session running a persistent interactive bash"""
        self._ensure_init_file()
        server = libtmux.Server()
        name = "manus-shell-" + re.sub(r"[^a-zA-Z0-9_-]", "-", session_id)
        session = server.new_session(
            session_name=name,
            start_directory=start_dir,
            kill_session=True,
            x=1000,
            y=1000,
        )
        # Ensure new panes get a large scrollback (the initial pane was created
        # with the default history-limit, so replace it with a fresh window)
        session.set_option("history-limit", str(HISTORY_LIMIT), global_=True)
        initial_window = session.active_window
        window = session.new_window(
            window_name="bash",
            window_shell=f"/bin/bash --rcfile {INIT_FILE}",
            start_directory=start_dir,
        )
        pane = window.active_pane
        initial_window.kill()

        # Wait for bash to come up (first PS1 sentinel rendered)
        deadline = time.monotonic() + 15
        while time.monotonic() < deadline:
            if self._parse_blocks(self._capture_sync(pane)):
                return session, pane
            time.sleep(0.1)
        raise AppException(message="Shell session failed to initialize")

    def _kill_tmux_session(self, shell: Dict[str, Any]) -> None:
        try:
            shell["tmux_session"].kill()
        except Exception:
            logger.warning("Failed to kill tmux session", exc_info=True)

    # ------------------------------------------------------------------
    # Output tracking
    # ------------------------------------------------------------------

    def _extract_output(self, raw: str, sent_text: str) -> str:
        """Strip the echoed command from a captured pane segment"""
        text = raw.lstrip("\r\n")
        if text.startswith(sent_text):
            text = text[len(sent_text):]
            if text.startswith("\r\n"):
                text = text[2:]
            elif text.startswith("\n"):
                text = text[1:]
        else:
            # Echo did not match exactly (readline artifacts); drop as many
            # lines as the command spans
            sent_lines = max(1, len(sent_text.splitlines()))
            text = "\n".join(text.splitlines()[sent_lines:])
        return text.rstrip()

    def _refresh_sync(self, shell: Dict[str, Any]) -> None:
        """Re-read the tmux pane and update current command state/output"""
        try:
            content = self._capture_sync(shell["pane"])
        except ShellDeadError:
            # bash exited (e.g. the user ran `exit`); finalize gracefully
            shell["dead"] = True
            cur = shell.get("current")
            if cur is not None and not cur["done"]:
                cur["done"] = True
                cur["returncode"] = 0
                shell["last_returncode"] = 0
            return

        blocks = self._parse_blocks(content)
        if blocks:
            meta = blocks[-1][1]
            shell["meta"] = meta
            if meta.get("working_dir"):
                shell["last_cwd"] = meta["working_dir"]

        cur = shell.get("current")
        if cur is None or cur["done"]:
            return

        k = cur["k"]
        idle = content.rstrip().endswith(PS1_END)
        completing = None
        prompt_block = None
        if len(blocks) > k:
            prompt_block = blocks[k - 1][0]
            completing = blocks[k]
        elif blocks and len(blocks) >= k:
            prompt_block = blocks[k - 1][0]
        elif blocks:
            # History overflowed and earlier prompts were dropped; approximate
            if idle:
                completing = blocks[-1]
                prompt_block = blocks[-2][0] if len(blocks) >= 2 else None
            else:
                prompt_block = blocks[-1][0]

        start = prompt_block.end() if prompt_block is not None else 0
        if completing is not None:
            raw = content[start:completing[0].start()]
            cur["done"] = True
            try:
                cur["returncode"] = int(completing[1].get("exit_code", -1))
            except (TypeError, ValueError):
                cur["returncode"] = -1
            shell["last_returncode"] = cur["returncode"]
        else:
            raw = content[start:]

        output = self._remove_ansi_escape_codes(self._extract_output(raw, cur["sent_text"]))
        cur["output"] = output
        if shell["console"]:
            shell["console"][-1].output = output

    async def _refresh(self, shell: Dict[str, Any]) -> None:
        await asyncio.to_thread(self._refresh_sync, shell)

    async def _locked_refresh(self, shell: Dict[str, Any]) -> None:
        async with shell["lock"]:
            await self._refresh(shell)

    async def _poll_until_done(self, shell: Dict[str, Any], timeout: float) -> bool:
        """Poll the pane until the current command completes or timeout.

        The session lock is only held for each refresh, so concurrent
        view_shell calls (live terminal streaming) are never starved.
        """
        deadline = time.monotonic() + timeout
        while True:
            await self._locked_refresh(shell)
            cur = shell.get("current")
            if cur is None or cur["done"]:
                return True
            if time.monotonic() >= deadline:
                return False
            await asyncio.sleep(0.2)

    async def _run_hidden(self, shell: Dict[str, Any], command: str, timeout: float = 10) -> None:
        """Run a housekeeping command (e.g. cd) without recording it in console"""
        pane = shell["pane"]
        async with shell["lock"]:
            blocks_before = len(self._parse_blocks(await asyncio.to_thread(self._capture_sync, pane)))
            await asyncio.to_thread(pane.send_keys, command, enter=True, literal=True)
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            content = await asyncio.to_thread(self._capture_sync, pane)
            if len(self._parse_blocks(content)) > blocks_before:
                await self._locked_refresh(shell)
                return
            await asyncio.sleep(0.1)
        raise AppException(message=f"Timed out running internal command: {command}")

    async def _interrupt(self, shell: Dict[str, Any], timeout: float = 3.0) -> bool:
        """Send Ctrl-C to the foreground process and wait for the prompt"""
        pane = shell["pane"]
        async with shell["lock"]:
            await asyncio.to_thread(pane.send_keys, "C-c", enter=False, literal=False)
        return await self._poll_until_done(shell, timeout)

    async def _ensure_shell(self, session_id: str, exec_dir: str) -> Dict[str, Any]:
        """Get or (re)create the persistent shell for a session"""
        async with self._create_lock:
            shell = self.active_shells.get(session_id)
            if shell is not None and not shell.get("dead"):
                return shell

            tmux_session, pane = await asyncio.to_thread(
                self._create_tmux_shell_sync, session_id, exec_dir
            )
            if shell is None:
                shell = {
                    "console": [],
                    "lock": asyncio.Lock(),
                    "last_returncode": 0,
                }
                self.active_shells[session_id] = shell
            shell.update({
                "tmux_session": tmux_session,
                "pane": pane,
                "current": None,
                "meta": None,
                "last_cwd": exec_dir,
                "dead": False,
            })
            await self._refresh(shell)
            return shell

    def _current_output(self, shell: Dict[str, Any]) -> str:
        cur = shell.get("current")
        return cur["output"] if cur else ""

    # ------------------------------------------------------------------
    # Public API (same contract as before)
    # ------------------------------------------------------------------

    async def exec_command(self, session_id: str, exec_dir: Optional[str], command: str) -> ShellExecResult:
        """
        Execute a command in the persistent shell of the specified session
        """
        logger.info(f"Executing command in session {session_id}: {command}")
        start_dir = exec_dir or os.path.expanduser("~")
        if not os.path.exists(start_dir):
            logger.error(f"Directory does not exist: {start_dir}")
            raise BadRequestException(f"Directory does not exist: {start_dir}")

        try:
            shell = await self._ensure_shell(session_id, start_dir)
        except AppException:
            raise
        except Exception as e:
            logger.error(f"Failed to create shell session: {str(e)}", exc_info=True)
            raise AppException(
                message=f"Command execution failed: {str(e)}",
                data={"session_id": session_id, "command": command}
            )

        try:
            await self._locked_refresh(shell)
            cur = shell.get("current")
            if cur is not None and not cur["done"]:
                # A previous command is still running — interrupt it first
                # (matches the old behavior of replacing the running process)
                logger.debug(f"Interrupting previous command in session: {session_id}")
                if not await self._interrupt(shell):
                    logger.warning(f"Ctrl-C did not stop previous command in session: {session_id}")
                    await self._hard_reset(shell, session_id, start_dir)

            # Honor exec_dir while keeping the shell stateful: only cd when
            # the caller asked for a directory different from the current one
            if exec_dir and not shell.get("dead"):
                current_dir = os.path.normpath(shell.get("last_cwd") or "")
                if current_dir != os.path.normpath(exec_dir):
                    await self._run_hidden(shell, f"cd {shlex.quote(exec_dir)}")

            if shell.get("dead"):
                shell = await self._ensure_shell(session_id, start_dir)

            async with shell["lock"]:
                pane = shell["pane"]
                ps1 = self._format_ps1(shell)
                content = await asyncio.to_thread(self._capture_sync, pane)
                blocks_before = len(self._parse_blocks(content))

                await asyncio.to_thread(pane.send_keys, command, enter=True, literal=True)
                shell["current"] = {
                    "command": command,
                    "sent_text": command,
                    "k": blocks_before,
                    "done": False,
                    "returncode": None,
                    "output": "",
                }
                shell["console"].append(ConsoleRecord(ps1=ps1, command=command, output=""))

            # Soft wait (same 5s window as before) for fast commands
            if await self._poll_until_done(shell, timeout=5):
                cur = shell["current"]
                logger.debug(f"Command completed with code: {cur['returncode']}")
                return ShellExecResult(
                    session_id=session_id,
                    command=command,
                    status="completed",
                    returncode=cur["returncode"],
                    output=cur["output"],
                )

            logger.debug(f"Command still running after soft wait in session: {session_id}")
            return ShellExecResult(
                session_id=session_id,
                command=command,
                status="running",
            )
        except (AppException, BadRequestException, ResourceNotFoundException):
            raise
        except Exception as e:
            logger.error(f"Command execution failed: {str(e)}", exc_info=True)
            raise AppException(
                message=f"Command execution failed: {str(e)}",
                data={"session_id": session_id, "command": command}
            )

    async def _hard_reset(self, shell: Dict[str, Any], session_id: str, start_dir: str) -> None:
        """Kill and recreate the tmux session, preserving console history"""
        cur = shell.get("current")
        if cur is not None and not cur["done"]:
            cur["done"] = True
            cur["returncode"] = -9
            shell["last_returncode"] = -9
        await asyncio.to_thread(self._kill_tmux_session, shell)
        shell["dead"] = True
        await self._ensure_shell(session_id, start_dir)

    async def view_shell(self, session_id: str, console: bool = False) -> ShellViewResult:
        """
        View the current command output of the specified shell session
        """
        logger.debug(f"Viewing shell content for session: {session_id}")
        if session_id not in self.active_shells:
            logger.error(f"Session ID not found: {session_id}")
            raise ResourceNotFoundException(f"Session ID does not exist: {session_id}")

        shell = self.active_shells[session_id]
        await self._locked_refresh(shell)
        output = self._current_output(shell)

        if console:
            console_records = self.get_console_records(session_id)
        else:
            console_records = None

        return ShellViewResult(
            output=output,
            session_id=session_id,
            console=console_records
        )

    def get_console_records(self, session_id: str) -> List[ConsoleRecord]:
        """
        Get command console records for the specified session
        """
        logger.debug(f"Getting console records for session: {session_id}")
        if session_id not in self.active_shells:
            logger.error(f"Session ID not found: {session_id}")
            raise ResourceNotFoundException(f"Session ID does not exist: {session_id}")

        raw_console = self.active_shells[session_id]["console"]
        clean_console = []
        for record in raw_console:
            clean_console.append(ConsoleRecord(
                ps1=record.ps1,
                command=record.command,
                output=self._remove_ansi_escape_codes(record.output)
            ))
        return clean_console

    async def wait_for_process(self, session_id: str, seconds: Optional[int] = None) -> ShellWaitResult:
        """
        Wait for the current command in the specified shell session to finish
        """
        logger.debug(f"Waiting for command in session: {session_id}, timeout: {seconds}s")
        if session_id not in self.active_shells:
            logger.error(f"Session ID not found: {session_id}")
            raise ResourceNotFoundException(f"Session ID does not exist: {session_id}")

        shell = self.active_shells[session_id]
        if seconds is None:
            seconds = 60

        if await self._poll_until_done(shell, timeout=seconds):
            cur = shell.get("current")
            returncode = cur["returncode"] if cur and cur["returncode"] is not None else shell["last_returncode"]
            logger.info(f"Command completed with return code: {returncode}")
            return ShellWaitResult(returncode=returncode)

        logger.warning(f"Command wait timeout expired: {seconds}s")
        raise BadRequestException(f"Wait timeout: {seconds} seconds")

    async def write_to_process(self, session_id: str, input_text: str, press_enter: bool) -> ShellWriteResult:
        """
        Write input to the running command in the specified shell session
        """
        logger.debug(f"Writing to session: {session_id}, press_enter: {press_enter}")
        if session_id not in self.active_shells:
            logger.error(f"Session ID not found: {session_id}")
            raise ResourceNotFoundException(f"Session ID does not exist: {session_id}")

        shell = self.active_shells[session_id]
        async with shell["lock"]:
            await self._refresh(shell)
            cur = shell.get("current")
            if cur is None or cur["done"]:
                logger.error("No running command, cannot write input")
                raise BadRequestException("Process has ended, cannot write input")

            try:
                pane = shell["pane"]
                if not press_enter and SPECIAL_KEY_REGEX.match(input_text):
                    # Allow sending control keys such as C-c / C-d
                    await asyncio.to_thread(pane.send_keys, input_text, enter=False, literal=False)
                else:
                    await asyncio.to_thread(pane.send_keys, input_text, enter=press_enter, literal=True)
                logger.info("Successfully wrote input to shell")
                return ShellWriteResult(status="success")
            except Exception as e:
                logger.error(f"Failed to write input: {str(e)}", exc_info=True)
                raise AppException(message=f"Failed to write input: {str(e)}")

    async def kill_process(self, session_id: str) -> ShellKillResult:
        """
        Terminate the running command in the specified shell session.
        The shell session itself stays alive (real-shell semantics).
        """
        logger.info(f"Killing command in session: {session_id}")
        if session_id not in self.active_shells:
            logger.error(f"Session ID not found: {session_id}")
            raise ResourceNotFoundException(f"Session ID does not exist: {session_id}")

        shell = self.active_shells[session_id]
        try:
            await self._locked_refresh(shell)
            cur = shell.get("current")
            if cur is None or cur["done"]:
                returncode = cur["returncode"] if cur and cur["returncode"] is not None else shell["last_returncode"]
                logger.info(f"No running command, last return code: {returncode}")
                return ShellKillResult(
                    status="already_terminated",
                    returncode=returncode
                )

            # Graceful: Ctrl-C (twice), then hard reset the tmux session
            if not await self._interrupt(shell, timeout=3.0):
                logger.warning("Ctrl-C did not stop the command, retrying")
                if not await self._interrupt(shell, timeout=2.0):
                    logger.warning("Forcefully recreating the shell session")
                    await self._hard_reset(
                        shell, session_id,
                        shell.get("last_cwd") or os.path.expanduser("~")
                    )

            cur = shell.get("current")
            returncode = cur["returncode"] if cur and cur["returncode"] is not None else -9
            logger.info(f"Command terminated with return code: {returncode}")
            return ShellKillResult(
                status="terminated",
                returncode=returncode
            )
        except (AppException, BadRequestException, ResourceNotFoundException):
            raise
        except Exception as e:
            logger.error(f"Failed to kill command: {str(e)}", exc_info=True)
            raise AppException(message=f"Failed to terminate process: {str(e)}")

    def create_session_id(self) -> str:
        """
        Create a new session ID
        """
        session_id = str(uuid.uuid4())
        logger.debug(f"Created new session ID: {session_id}")
        return session_id

shell_service = ShellService()
